name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: rush setup
      run: |
        node common/scripts/install-run-rush.js install
        rush change -v
        rush install --no-link
        rush link
      env:
        CI: true
    - name: build
      run: |
        rush rebuild --verbose
      env:
        CI: true
    - name: code style
      run: |
        rush tslint
        rush prettier
      env:
        CI: true
    - name: test
      run: |
        npm run test:all
      env:
        CI: true
