name: Build/Test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: rush setup
      run: |
        node common/scripts/install-run-rush.js install
        rush change -v
        rush install --no-link
        rush link
        rush rebuild --ship --verbose
      env:
        CI: true
    - name: rush test
      run: |
        rush test
      env:
        CI: true
