name: Build/Test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: rush setup
      run: |
        npm i -g @microsoft/rush
        rush check
        rush update
      env:
        CI: true
    - name: rush build
      run: |
        rush rebuild
      env:
        CI: true
    - name: code style
      run: |
        rush tslint
        rush prettier
      env:
        CI: true
    - name: rush test
      run: |
        rush test
      env:
        CI: true
